### ISSUE TITLE
Troubles setting up the framework

### ISSUE THREAD

**Issue by genesys2** [mupq/pqriscv#5]
Hi,

I am having some troubles setting up the framework. First, I believe there is a missing dependency int the PQVexRiscV readme for yosys. I installed it from here and it seems to work: https://github.com/YosysHQ/yosys

My main problem is, that `./build_everything` results in an error. If I run the command from the root directory, this is the output:
````
/home/shared/pqriscv$ ./build_everything.py
Traceback (most recent call last):
  File "/home/shared/pqriscv/mupq/mupq.py", line 113, in get_implementations
    for scheme in os.listdir(scheme_folder):
FileNotFoundError: [Errno 2] No such file or directory: 'crypto_kem'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./build_everything.py", line 14, in <module>
    mupq.BuildAll(settings).test_all(rest)
  File "/home/shared/pqriscv/mupq/mupq.py", line 242, in test_all
    for implementation in self.get_implementations():
  File "/home/shared/pqriscv/mupq/mupq.py", line 131, in get_implementations
    ) from e
Exception: There is no bin/ folder. Please first make binaries.
````

The script doesn't seem to find the crypto_kem folder which is in mupq/. Next, I tried running the script directly from the mupq folder with ´´../build_everything.py´´ which results in a different error:

````
/home/shared/pqriscv/mupq$ ../build_everything.py
INFO:Implementation:Building r5nd-5kemcca-0d - opt - test
make: *** No rule to make target 'bin/crypto_kem_r5nd-5kemcca-0d_opt_test.bin'.  Stop.
Traceback (most recent call last):
  File "../build_everything.py", line 14, in <module>
    mupq.BuildAll(settings).test_all(rest)
  File "/home/shared/pqriscv/mupq/mupq.py", line 247, in test_all
    if self.run_test(implementation) == -1:
  File "/home/shared/pqriscv/mupq/mupq.py", line 386, in run_test
    implementation.build_binary(test_type)
  File "/home/shared/pqriscv/mupq/mupq.py", line 74, in build_binary
    self.run_make(self.get_binary_path(type_))
  File "/home/shared/pqriscv/mupq/mupq.py", line 67, in run_make
    return subprocess.check_call(makeflags)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'IMPLEMENTATION_PATH=crypto_kem/r5nd-5kemcca-0d/opt', 'PLATFORM=vexriscv', 'VEXRISCV_PLATFORM=pqvexriscvup5k', 'bin/crypto_kem_r5nd-5kemcca-0d_opt_test.bin']' returned non-zero exit status 2.
````

I also tried copying the Makefile from the root directory to mupq/, resulting in yet another error:
````
/home/shared/pqriscv/mupq$ ../build_everything.py
INFO:Implementation:Building r5nd-5kemcca-0d - opt - test
Makefile:6: common/vexriscv.mk: No such file or directory
make: *** No rule to make target 'common/vexriscv.mk'.  Stop.
Traceback (most recent call last):
  File "../build_everything.py", line 14, in <module>
    mupq.BuildAll(settings).test_all(rest)
  File "/home/shared/pqriscv/mupq/mupq.py", line 247, in test_all
    if self.run_test(implementation) == -1:
  File "/home/shared/pqriscv/mupq/mupq.py", line 386, in run_test
    implementation.build_binary(test_type)
  File "/home/shared/pqriscv/mupq/mupq.py", line 74, in build_binary
    self.run_make(self.get_binary_path(type_))
  File "/home/shared/pqriscv/mupq/mupq.py", line 67, in run_make
    return subprocess.check_call(makeflags)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'IMPLEMENTATION_PATH=crypto_kem/r5nd-5kemcca-0d/opt', 'PLATFORM=vexriscv', 'VEXRISCV_PLATFORM=pqvexriscvup5k', 'bin/crypto_kem_r5nd-5kemcca-0d_opt_test.bin']' returned non-zero exit status 2.
````

I would try copying the common/ folder from the root directory as well but there is already a common folder so things would start getting a bit messy... 

Any idea how I can solve this issue? 
Thank you!

**Comment by rpls** [comment]
The build system looks for ciphers and implementations in the `crypto_{kem,sign}` (RISC-V Specific implementations) folders, as well as in the `mupq/crypto_{kem,sign}` (for generic C implementations) and `mupq/pqclean/crypto_{kem,sign}` (for cleaned up generic C implementations) folders. Just add empty `crypto_kem`/`crypto_sign` folders. I simply forgot to add them (just pushed empty files for them now), as we haven't added any RISC-V specific implementations for now (we will soon add Newhope and Kyber implementations).

You have to execute the `build_everything.py` script from the pqriscv folder (will work now with `crypto_{kem,sign}` folders present), not the `mupq` folder.

As for the yosys dependency, the `pqriscv-vexriscv` repository mentions the [Project Icestorm toolchain](http://www.clifford.at/icestorm/) as a dependency, which includes `yosys`. Although strictly speaking, the Icestorm toolchain isn't required, you _could_ also use manufacturers toolchain to synthesize the FPGA bitstreams for the iCE40 FPGAs. For the VexRiscV simulator in `pqriscv-vexriscv` you shoud not require any FPGA toolchain, just a Java JDK, `sbt`, and `verilator`.

**Comment by genesys2** [comment]
Thank you for the quick response! Adding the empty folders in the root directory worked :-) 

Regarding the yosys dependency, I skipped Icestorm since I use a Xilinx FPGA but still, it works. Thank you!
